In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
warnings.filterwarnings('ignore')

In [83]:
df = sns.load_dataset("titanic")

In [84]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [85]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    str     
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    str     
 8   class        891 non-null    category
 9   who          891 non-null    str     
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str     
 13  alive        891 non-null    str     
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 100.4 KB


In [87]:
df.drop(["deck", "embark_town", "alive", "class", "who", "adult_male"], axis=1, inplace=True)

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    str    
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    str    
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 61.8 KB


In [89]:
df["age"] = df["age"].fillna(df["age"].mean())

In [90]:
df.dropna(subset=["embarked"], inplace=True)

In [91]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    str    
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    str    
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), str(2)
memory usage: 68.5 KB


In [92]:
le = LabelEncoder()

In [93]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True


In [94]:
df['sex'] = le.fit_transform(df['sex'])
df["embarked"] = le.fit_transform(df["embarked"])

In [95]:
df["alone"] = df["alone"].astype(int)
df["age"] = df["age"].astype(int)
df["fare"] = df["fare"].astype(int)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22,1,0,7,2,0
1,1,1,0,38,1,0,71,0,0
2,1,3,0,26,0,0,7,2,1
3,1,1,0,35,1,0,53,2,0
4,0,3,1,35,0,0,8,2,1


In [96]:
X = df.drop("survived", axis=1)
y = df["survived"]

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [98]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [99]:
y_pred = model.predict(X_test)

In [100]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [101]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [102]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]])

In [103]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [104]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [105]:
scale = StandardScaler()

In [106]:
X_train_scaled = scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)

In [107]:
X_train_scaled

array([[-1.58410418, -1.40530972, -0.58667407, ...,  2.42752104,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.35872483,
        -1.95246446, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.50108776,
         0.58770431,  0.81076671],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.13501166,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.66286134, ...,  0.04802639,
         0.58770431, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.4807502 ,
         0.58770431,  0.81076671]], shape=(711, 8))

In [108]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [109]:
model_knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [110]:
y_pred_knn = model_knn.predict(X_test_scaled)

In [111]:
y_pred_knn

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [112]:
confusion_matrix(y_test, y_pred_knn)

array([[89, 20],
       [17, 52]])

In [113]:
accuracy_score(y_test, y_pred_knn)

0.7921348314606742

In [114]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178



In [115]:
X_test

,pclass,sex,age,sibsp,parch,fare,embarked,alone
281,3,1,28,0,0,7,2,1
435,1,0,14,1,2,120,2,0
39,3,0,14,1,0,11,0,0
418,2,1,30,0,0,13,2,1
585,1,0,18,0,2,79,2,0
...,...,...,...,...,...,...,...,...
433,3,1,17,0,0,7,2,1
807,3,0,18,0,0,7,2,1
25,3,0,38,1,5,31,2,0
85,3,0,33,3,0,15,2,0


In [116]:
X_test_scaled

array([[ 0.8122747 ,  0.71158691, -0.12955049, ..., -0.50108776,
         0.58770431,  0.81076671],
       [-1.58410418, -1.40530972, -1.19617218, ...,  1.79705664,
         0.58770431, -1.23340042],
       [ 0.8122747 , -1.40530972, -1.19617218, ..., -0.41973751,
        -1.95246446, -1.23340042],
       ...,
       [ 0.8122747 , -1.40530972,  0.63232214, ..., -0.01298629,
         0.58770431, -1.23340042],
       [ 0.8122747 , -1.40530972,  0.25138582, ..., -0.33838727,
         0.58770431, -1.23340042],
       [ 0.8122747 , -1.40530972, -1.95804481, ..., -0.31804971,
         0.58770431, -1.23340042]], shape=(178, 8))

In [117]:
model_NB = GaussianNB()

In [118]:
model_NB.fit(X_train, y_train)

GaussianNB()

In [119]:
y_pred_NB = model_NB.predict(X_test)

In [120]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [121]:
accuracy_score(y_test, y_pred_NB)

0.7752808988764045

In [122]:
confusion_matrix(y_test, y_pred_NB)

array([[84, 25],
       [15, 54]])

In [123]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [124]:
model_DT = DecisionTreeClassifier()

In [125]:
model_DT.fit(X_train_scaled, y_train)

DecisionTreeClassifier()

In [126]:
y_pred_DT = model_DT.predict(X_test_scaled)

In [127]:
accuracy_score(y_test, y_pred_DT)

0.7808988764044944

In [128]:
confusion_matrix(y_test, y_pred_DT)

array([[87, 22],
       [17, 52]])

In [129]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

           0       0.84      0.80      0.82       109
           1       0.70      0.75      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [130]:
model_svm=SVC(kernel="rbf")

In [131]:
model_svm.fit(X_train_scaled, y_train)

SVC()

In [132]:
y_pred_svm=model_svm.predict(X_test_scaled)

In [133]:
accuracy_score(y_test, y_pred_svm)

0.8146067415730337

In [134]:
confusion_matrix(y_test, y_pred_svm)

array([[91, 18],
       [15, 54]])

In [135]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       109
           1       0.75      0.78      0.77        69

    accuracy                           0.81       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.81      0.82       178



## Implemented Using Cross Validation

In [136]:
df 

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22,1,0,7,2,0
1,1,1,0,38,1,0,71,0,0
2,1,3,0,26,0,0,7,2,1
3,1,1,0,35,1,0,53,2,0
4,0,3,1,35,0,0,8,2,1
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1
887,1,1,0,19,0,0,30,2,1
888,0,3,0,29,1,2,23,2,0
889,1,1,1,26,0,0,30,0,1


In [137]:
X=df.drop('survived', axis= 1)
y=df['survived']

In [138]:
from sklearn.model_selection import cross_val_score

In [139]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [140]:
scores=cross_val_score(model_svm, X_scaled, y, cv=5, scoring='accuracy')

In [141]:
scores

array([0.83146067, 0.82022472, 0.81460674, 0.80898876, 0.86440678])

In [142]:
print(scores.mean())

0.8279375357074844


## Using Boosting Techniques

In [143]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [144]:
from xgboost import XGBClassifier

In [145]:
ada_model=AdaBoostClassifier(n_estimators=100, random_state=42)

In [146]:
ada_model.fit(X_train_scaled, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [147]:
y_pred_ada=ada_model.predict(X_test_scaled)

In [148]:
accuracy_score(y_test, y_pred_ada)

0.8202247191011236

In [149]:
gb_model=GradientBoostingClassifier(n_estimators=100, random_state=42)

In [150]:
gb_model.fit(X_train_scaled, y_train)

GradientBoostingClassifier(random_state=42)

In [151]:
y_pred_gb=gb_model.predict(X_test_scaled)

In [152]:
accuracy_score(y_test, y_pred_gb)

0.8146067415730337

In [153]:
xgb_model=XGBClassifier(n_estimators=100, random_state=42)

In [154]:
xgb_model.fit(X_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [155]:
y_pred_xgb=xgb_model.predict(X_test_scaled)

In [156]:
accuracy_score(y_test, y_pred_xgb)

0.8202247191011236